version: "3.7"

services:
  {{cookiecutter.project_slug}}-api:
    build:
      context: .
    environment:
      CREATE_DATABASE: ${CREATE_DATABASE-true}
      ENV_FOR_DYNACONF: docker
    image: {{cookiecutter.project_slug}}/api
    container_name: {{cookiecutter.project_slug}}-api
    command: sh -c './wait-for-pg.sh -t 30 db:5432 -- ./docker_start.sh'
    ports:
      - '4000:4000'
    depends_on:
      - docker_db
    networks:
      - postgres_network

  docker_db:
    image: postgres:11.3-alpine
    container_name: {{cookiecutter.project_slug}}-docker_db
    restart: always
    environment:
      - POSTGRES_DB={{cookiecutter.project_slug}}_db
      - POSTGRES_USER={{cookiecutter.project_slug}}_user
      - POSTGRES_PASSWORD=IWKdrWWnc6XA39pgX6PU
    volumes:
        - postgres_{{cookiecutter.project_slug}}_docker:/var/lib/postgresql/data
    networks:
      postgres_network:
         aliases:
            - db
  
  development_db:
    container_name: {{cookiecutter.project_slug}}-development_db
    image: postgres:11.3-alpine
    environment:
      - POSTGRES_DB={{cookiecutter.project_slug}}_db
      - POSTGRES_USER={{cookiecutter.project_slug}}_user
      - POSTGRES_PASSWORD=IWKdrWWnc6XA39pgX6PU
    volumes:
        - postgres_{{cookiecutter.project_slug}}_dev:/var/lib/postgresql/data
    ports:
      - "5453:5432" 

  test_db:
    container_name: {{cookiecutter.project_slug}}-test_db
    image: postgres:11.3-alpine
    environment:
      - POSTGRES_DB={{cookiecutter.project_slug}}_db
      - POSTGRES_USER={{cookiecutter.project_slug}}_user
      - POSTGRES_PASSWORD=IWKdrWWnc6XA39pgX6PU
    volumes:
        - postgres_{{cookiecutter.project_slug}}_test:/var/lib/postgresql/data
    ports:
      - "5454:5432"


volumes:
  postgres_{{cookiecutter.project_slug}}_docker:
    driver: local
    name: postgres_{{cookiecutter.project_slug}}_docker

  postgres_{{cookiecutter.project_slug}}_test:
    driver: local
    name: postgres_{{cookiecutter.project_slug}}_test

  postgres_{{cookiecutter.project_slug}}_dev:
    driver: local
    name: postgres_{{cookiecutter.project_slug}}_dev
          

networks:
  postgres_network:
    driver: bridge